### ISSUE TITLE
unable  to scroll down for the rest of the web page

### ISSUE THREAD

**Issue by athom** [koron/ssserver#2]
any plan to support that?

**Comment by koron** [comment]
I have no idea.  But when anyone find the method (and pull request 😉), I'll merge it.

**Comment by koron** [comment]
I have implemented `sY` (and `sX`) options.

@athom Please try it.

**Comment by athom** [comment]
@koron awesome work!
is it possible to scroll smartly without specifying the `sY`?
I think it's a pretty common usage to capture the whole page, most of the time the sY is not known yet.

**Comment by athom** [comment]
base on the latest modification, it only render the latest scroll zone, scrolled pages wont be render. 
I think it was not expected.
  
for example: when `sY` is at the border of B,C, it only B will be captured, I suppose that A and B will be both captured. 

```
______
|   A   |
|   B  |
|   C  |
|____|
```

**Comment by koron** [comment]
how about capture twice or more and join images?

**Comment by koron** [comment]
@athom now `full` is added for full page screenshot. please try it.

**Comment by athom** [comment]
@koron thank you for your work.
I had checked out the latest source code and tried it again. 
Unfortunately, it did not work.

version:

```
commit dd89689501cc4a71bf58dce86b4a8eb2cf168516
Refs: master, <origin/HEAD>, <origin/master>
Author:     MURAOKA Taro <koron.kaoriya@gmail.com>
AuthorDate: Tue Jan 16 23:04:46 2018 +0900
Commit:     MURAOKA Taro <koron.kaoriya@gmail.com>
CommitDate: Tue Jan 16 23:04:46 2018 +0900
```

Step1:  `go run main.go`

Step2:  Follow your readme guide
`$ curl -v 'http://127.0.0.1:3000/?u=https://www.kaoriya.net/&full' -o kaoriya-full.png`

Result:

![image](https://user-images.githubusercontent.com/85204/35387899-90ee32ec-020c-11e8-9d6c-64ea9ea504b8.png)

**Comment by koron** [comment]
@athom Hmm, something strange.

Please check size (width & height) of your kaoriya-full.png

In my environment, it is 1024x1246

**Comment by athom** [comment]
yes, the same with you.

the info of kaoriya-full.png is:

83,698 bytes 
1024 × 1246

maybe need more drivers?
